/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package in.scalive.gui.swingbuilder;

import java.awt.Color;

/**
 *
 * @author LENOVO
 */
public class ColorChangingViacheckBox extends javax.swing.JFrame {
    private int red;
    private int blue;
    private int green;
    /**
     * Creates new form ColorChangingViaButtons
     */
    public ColorChangingViacheckBox() {
        initComponents();
        super.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basePanel = new javax.swing.JPanel();
        jcbRed = new javax.swing.JCheckBox();
        jcbGreen = new javax.swing.JCheckBox();
        jcbBlue = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        basePanel.setBackground(new java.awt.Color(0, 0, 0));

        jcbRed.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jcbRed.setForeground(new java.awt.Color(255, 255, 255));
        jcbRed.setText("Red");
        jcbRed.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        jcbRed.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbRedItemStateChanged(evt);
            }
        });

        jcbGreen.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jcbGreen.setForeground(new java.awt.Color(255, 255, 255));
        jcbGreen.setText("Green");
        jcbGreen.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        jcbGreen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbGreenItemStateChanged(evt);
            }
        });

        jcbBlue.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jcbBlue.setForeground(new java.awt.Color(255, 255, 255));
        jcbBlue.setText("Blue");
        jcbBlue.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        jcbBlue.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbBlueItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout basePanelLayout = new javax.swing.GroupLayout(basePanel);
        basePanel.setLayout(basePanelLayout);
        basePanelLayout.setHorizontalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jcbRed, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jcbGreen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jcbBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        basePanelLayout.setVerticalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePanelLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbRed)
                    .addComponent(jcbGreen)
                    .addComponent(jcbBlue))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void changeColor(){
        basePanel.setBackground(new Color(red,green,blue));
        if(red==green && green == blue){
            if(red==0){
                jcbRed.setForeground(Color.WHITE);
                jcbBlue.setForeground(Color.WHITE);
                jcbGreen.setForeground(Color.WHITE);
            }else{
                jcbRed.setForeground(Color.BLACK);
                jcbBlue.setForeground(Color.BLACK);
                jcbGreen.setForeground(Color.BLACK);
            }
        }
    }
    private void jcbRedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbRedItemStateChanged
        if(jcbRed.isSelected()){
            red=255;
        }else{
            red=0;
        }
        changeColor();
    }//GEN-LAST:event_jcbRedItemStateChanged

    private void jcbGreenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbGreenItemStateChanged
        if(jcbGreen.isSelected()){
            green=255;
        }else{
            green=0;
        }
        changeColor();
    }//GEN-LAST:event_jcbGreenItemStateChanged

    private void jcbBlueItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbBlueItemStateChanged
        if(jcbBlue.isSelected()){
            blue=255;
        }else{
            blue=0;
        }
        changeColor();
    }//GEN-LAST:event_jcbBlueItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColorChangingViacheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColorChangingViacheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColorChangingViacheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColorChangingViacheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColorChangingViacheckBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basePanel;
    private javax.swing.JCheckBox jcbBlue;
    private javax.swing.JCheckBox jcbGreen;
    private javax.swing.JCheckBox jcbRed;
    // End of variables declaration//GEN-END:variables
}
