/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package in.scalive.gui.swingbuilder;

import in.scalive.myexceptions.ColorNotSelectedException;
import java.awt.Color;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class JListDemo1 extends javax.swing.JFrame {

    /**
     * Creates new form JListDemo1
     */
    private DefaultListModel dlm;
    private Map<String, Color> colors=new HashMap<>();
    public JListDemo1() {
        initComponents();
        dlm=new DefaultListModel();
        jlColors.setModel(dlm);
        setLocationRelativeTo(null);
        colors.put("Red", Color.RED);
        colors.put("Blue", Color.blue);
        colors.put("Green",Color.GREEN);
        colors.put("Cyan", Color.CYAN);
        colors.put("Pink", Color.PINK);
        colors.put("Magenta", Color.MAGENTA);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBase = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlColors = new javax.swing.JList<>();
        btnAddColors = new javax.swing.JButton();
        btnShowColor = new javax.swing.JButton();
        btnRemoveColor = new javax.swing.JButton();
        btnApply = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlColors.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jlColors.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jlColors);

        btnAddColors.setText("Add Colors");
        btnAddColors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddColorsActionPerformed(evt);
            }
        });

        btnShowColor.setText("Show Color");
        btnShowColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowColorActionPerformed(evt);
            }
        });

        btnRemoveColor.setText("Remove Color");
        btnRemoveColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveColorActionPerformed(evt);
            }
        });

        btnApply.setText("Apply");
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });

        lblResult.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout panelBaseLayout = new javax.swing.GroupLayout(panelBase);
        panelBase.setLayout(panelBaseLayout);
        panelBaseLayout.setHorizontalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBaseLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBaseLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBaseLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRemoveColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnShowColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddColors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnApply, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        panelBaseLayout.setVerticalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBaseLayout.createSequentialGroup()
                .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBaseLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBaseLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnAddColors)
                        .addGap(28, 28, 28)
                        .addComponent(btnShowColor)
                        .addGap(37, 37, 37)
                        .addComponent(btnRemoveColor)
                        .addGap(31, 31, 31)
                        .addComponent(btnApply)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddColorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddColorsActionPerformed
        Set<String> tempSet=colors.keySet();
        Iterator it=tempSet.iterator();
        while(it.hasNext()){
            dlm.addElement(it.next());
        }
    }//GEN-LAST:event_btnAddColorsActionPerformed

    private void btnRemoveColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveColorActionPerformed
                                             
        int index=jlColors.getSelectedIndex();
        try{
            if(index==-1){
                ColorNotSelectedException e=new ColorNotSelectedException("Please select a color first");
                throw e;
//                throw new NullPointerException("Please select a color first");
            }
            lblResult.setText("You selecetd "+jlColors.getSelectedValue());
            dlm.remove(index);
            colors.remove(jlColors.getSelectedValue());
        }catch(ColorNotSelectedException e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            e.printStackTrace();
            return;
        }
    }//GEN-LAST:event_btnRemoveColorActionPerformed

    private void btnShowColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowColorActionPerformed
        String selectedColorName=jlColors.getSelectedValue();
        try{
            if(selectedColorName==null){
                ColorNotSelectedException e=new ColorNotSelectedException("Please select a color first");
                throw e;
//                throw new NullPointerException("Please select a color first");
            }
            lblResult.setText("You selecetd "+selectedColorName);
        }catch(ColorNotSelectedException e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            e.printStackTrace();
            return;
        }
        
    }//GEN-LAST:event_btnShowColorActionPerformed

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
        String selectedColorName=jlColors.getSelectedValue();
        try{
            if(selectedColorName==null){
                ColorNotSelectedException e=new ColorNotSelectedException("Please select a color first");
                throw e;
//                throw new NullPointerException("Please select a color first");
            }
            lblResult.setText("You selecetd "+selectedColorName);
            panelBase.setBackground(colors.get(selectedColorName));
        }catch(ColorNotSelectedException e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            e.printStackTrace();
            return;
        }
    }//GEN-LAST:event_btnApplyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JListDemo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JListDemo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JListDemo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JListDemo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JListDemo1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddColors;
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnRemoveColor;
    private javax.swing.JButton btnShowColor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> jlColors;
    private javax.swing.JLabel lblResult;
    private javax.swing.JPanel panelBase;
    // End of variables declaration//GEN-END:variables
}
